const domStrings = {
    getStartedBtn :'.splash-screen__button',
    spalshScreen :'.splash-screen',
    signInScreen : '.sign-in',
    newUserBtn : '.new-user',
    signUpScreen : '.sign-up',
    register: '#reg-btn',
    welcomeScreen: '.welcome-screen',
    saveTrip : '.save-trip',
    saveTripBtn : '#save-trip-btn',
    cancelTrip: '.cancel-trip',
    tripScreen: '.trip',
    tripsListScreen: '.trips-list',
    humberger: '.humberger-toggle',
    mobileMenu: '.trip__menu',
    addTripBtn: 'add-trip',
    sections: 'section',
    nameInput: '#sign-in-name',
    psswInput: '#sign-in-pssw',
    login: '#login-btn',
    newNameInput: '#sign-up-name',
    newPassInput: '#sign-up-pssw',
    confPassInput: '#confirm-pssw',
    userNameHeader: '.welcome-screen__greetings',
    tripCity: '#trip-city',
    tripCountry: '#trip-country',
    departingTime: '#departing-time',
    departingDate: '#departing-date',
    tripDestination: '.trip__to h1',
    tripDestinationImg: '.trip__img',
    tripDestinationWether: '.trip__weather',
    tripToDestinationCounter: '.trip__counter',
    tripDestinationWeatherIcon: '.trip__wether-icon img',
    tripContainer: '.trip__container',
    tripTabbar: '.trip__tabbar',
    logout: '#logout-btn',
    yourTripsList: '.your-trips-list-btn',
    addItem: '.packing__add-item',
    addItemForm: '.add-item',
    addItemToPacking: '#add-item-btn',
    itemInput: '#item',
    itemQntInput: '#item-qnt',
    packingSection: '.packing',
    yourPacking: '.your-packing-btn',
    packingContainer: '.packing__container',
    backArrow: '#back-arrow',
}


const domItems = {
    getStarted: document.querySelector(domStrings.getStartedBtn),
    splashScreen: document.querySelector(domStrings.spalshScreen),
    signInScreen: document.querySelector(domStrings.signInScreen),
    newUser: document.querySelector(domStrings.newUserBtn),
    signUpScreen: document.querySelector(domStrings.signUpScreen),
    registerUser: document.querySelector(domStrings.register),
    welcomeScreen: document.querySelector(domStrings.welcomeScreen),
    saveTripScreen: document.querySelector(domStrings.saveTrip),
    saveTripBtn: document.querySelector(domStrings.saveTripBtn),
    cancelTrip: document.querySelector(domStrings.cancelTrip),
    tripScreen: document.querySelector(domStrings.tripScreen),
    tripsListScreen: document.querySelector(domStrings.tripsListScreen),
    humbergerMenu: document.querySelector(domStrings.humberger),
    mobileMenu: document.querySelector(domStrings.mobileMenu),
    addTripBtnByClass: document.querySelector(`.${domStrings.addTripBtn}`),
    addTripBtnById: document.getElementById(domStrings.addTripBtn),
    allSections: document.querySelectorAll(domStrings.sections),
    nameInput: document.querySelector(domStrings.nameInput),
    passwordInput: document.querySelector(domStrings.psswInput),
    loginBtn: document.querySelector(domStrings.login),
    newNameInput: document.querySelector(domStrings.newNameInput),
    newPasswordInput: document.querySelector(domStrings.newPassInput),
    confirmPasswordInput: document.querySelector(domStrings.confPassInput),
    userNameHeader: document.querySelector(domStrings.userNameHeader),
    tripCityInput: document.querySelector(domStrings.tripCity),
    tripCountryInput: document.querySelector(domStrings.tripCountry),
    tripDateInput: document.querySelector(domStrings.departingDate),
    tripTimeInput: document.querySelector(domStrings.departingTime),
    tripDestination: document.querySelector(domStrings.tripDestination),
    tripDestinationImg: document.querySelector(domStrings.tripDestinationImg),
    tripDestinationWether: document.querySelector(domStrings.tripDestinationWether),
    tripDestinationWeatherIcon: document.querySelector(domStrings.tripDestinationWeatherIcon),
    tripToDestinationCounter: document.querySelector(domStrings.tripToDestinationCounter),
    tripContainer: document.querySelector(domStrings.tripContainer),
    logoutBtn: document.querySelector(domStrings.logout),
    yourTripsListBtn: document.querySelector(domStrings.yourTripsList),
    addItemBtn: document.querySelector(domStrings.addItem),
    addItemForm: document.querySelector(domStrings.addItemForm),
    addItemToPackingBtn: document.querySelector(domStrings.addItemToPacking),
    itemInput: document.querySelector(domStrings.itemInput),
    itemQntInput: document.querySelector(domStrings.itemQntInput),
    packingSection: document.querySelector(domStrings.packingSection),
    yourPackingBtn: document.querySelector(domStrings.yourPacking),
    packingContainer: document.querySelector(domStrings.packingContainer),
    backArrow: document.querySelector(domStrings.backArrow),
    tripTabbar: document.querySelector(domStrings.tripTabbar)
}

export default domItems